{%- set yaml_metadata -%}
source_model: "stg_as400__lvfiscpf"
src_pk: "SUPPLIER_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "AARDC1"
    - "AKRTC1"
    - "BCLRC1"
    - "BETWC1"
    - "BIBUC1"
    - "BIDAC1"
    - "BLNDC1"
    - "BSPIC1"
    - "EANCC1"
    - "EXT1C1"
    - "EXT2C1"
    - "EXT3C1"
    - "GRPAC1"
    - "IBANC1"
    - "KAB3C1"
    - "KBPOC1"
    - "KRTCC1"
    - "KSTCC1"
    - "LANDC1"
    - "LSKDC1"
    - "LVSUC1"
    - "NMPLC1"
    - "NWB1C1"
    - "NWB2C1"
    - "NWB3C1"
    - "NWB4C1"
    - "OMS3C1"
    - "PLTSC1"
    - "PSPKC1"
    - "PSTKC1"
    - "REKNC2"
    - "RNRAC1"
    - "RWPLC1"
    - "SELKC1"
    - "SWFTC1"
    - "update_ident"
    - "START_DATETIME"
    - "END_DATETIME"
src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
