{{
  config(
    unique_key = ['FORECAST_HK', 'LOAD_DATETIME'],
    )
}}

{%- set yaml_metadata -%}
source_model: "stg_slim4__cdc_article_attributes"
src_pk: "FORECAST_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "abc"
    - "afzet_deze_periode"
    - "aantal_orders"
    - "aantal_maanden_obsolete"
    - "afzet_0"
    - "afzet_1"
    - "afzet_2"
    - "afzet_3"
    - "afzet_4"
    - "afzet_5"
    - "afzet_6"
    - "afzet_7"
    - "afzet_8"
    - "afzet_9"
    - "afzet_10"
    - "afzet_11"
    - "afzet_12"
    - "afzet_13"
    - "afzet_14"
    - "afzet_15"
    - "afzet_16"
    - "afzet_17"
    - "afzet_18"
    - "afzet_19"
    - "afzet_20"
    - "afzet_21"
    - "afzet_22"
    - "afzet_23"
    - "sales_class"
    - "afzet_lopende_week"
    - "afzet_vorige_week"
    - "art_gr"
    - "artikel_omschrijving"
    - "afgerond_besteladvies"
    - "basis_forecast"
    - "bd"
    - "besteladvies"
    - "besteladvies_genereren"
    - "besteld"
    - "bestelfreq"
    - "bestelfreq_bd_levdatum"
    - "bestelniveau"
    - "veiligheidsvoorraad"
    - "buffer_vrd"
    - "cover_tijd_m"
    - "cover_tijd_d"
    - "cover_tijd_w"
    - "dc_locatie"
    - "geimporteerde_eoq"
    - "excess_stock"
    - "f_test_waarde"
    - "forecast_1"
    - "forecast_2"
    - "forecast_3"
    - "forecast_4"
    - "forecast_5"
    - "forecast_6"
    - "forecast_7"
    - "forecast_8"
    - "forecast_9"
    - "forecast_10"
    - "forecast_11"
    - "forecast_12"
    - "folder_info"
    - "forecast_cp"
    - "forecast_cp_vrd"
    - "forecast_exception"
    - "geen_interesse_voorheen_boycot"
    - "gemiddelde_forecast"
    - "ijzeren_voorraad"
    - "ioq"
    - "importartikel"
    - "in_folder"
    - "laatste_afzet"
    - "laatste_maandverkoop"
    - "originele_leverancier"
    - "leveranciersnaam"
    - "levertijd_d"
    - "misorders_manco_lev"
    - "misorders_afgel_wk"
    - "moq"
    - "prijs"
    - "relevante_periode"
    - "bestelinterval_d"
    - "run_code"
    - "scp_naam"
    - "seizoen"
    - "seizoensstatus"
    - "seizoensprofiel"
    - "servicelevel"
    - "setting_ijzeren_vrd"
    - "tht_garantie"
    - "tht_pick"
    - "verkoopprijs"
    - "vest_voorraad_totaal"
    - "is_stock_controlled"
    - "stock_exception"
    - "voorraadmanager"
    - "fysieke_voorraad"
    - "vrd_min_best_per_max"
    - "werkelijk_te_bestellen"
    - "verstuurdatum"
    - "verstuurdatum_2"
    - "leverdatum"
    - "leverdatum_2"
    - "artikelgroep_omschrijving"
    - "abs_voorspelling"
    - "formule"
    - "st"
    - "totale_veiligheidsvoorraad"
    - "demandplanner_primair"
    - "nullev_leverancier"
    - "gtin"
    - "sales_class_short_description"
    - "sales_class_long_description"
    - "forecast_exception_short_description"
    - "forecast_exception_long_description"
    - "stock_exception_short_description"
    - "stock_exception_long_description"
    - "START_DATETIME"
src_ldts: "LOAD_DATETIME"
src_extra_columns:
    - "END_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ add_end_datetime_to_sat(metadata_dict) }}
