{%- set yaml_metadata -%}
source_model: "stg_as400__dwfkrcpf"
src_pk: "SALES_INVOICE_LINES_TRANSACTIONS_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "acaac1"
    - "ackbc1"
    - "ackdc1"
    - "acrfc1"
    - "alcpc1"
    - "alnrc1"
    - "aonrc1"
    - "arnrc1"
    - "bsaac1"
    - "btkdc1"
    - "cdalc1"
    - "cdnvc1"
    - "cokdc1"
    - "cretc1"
    - "dcaac1"
    - "dckdc1"
    - "dfpxc1"
    - "dvnmc1"
    - "dwjnc1"
    - "fanrc1"
    - "finrc1"
    - "fkdec1"
    - "fksrc1"
    - "foejc1"
    - "fokdc1"
    - "fonrc1"
    - "initc1"
    - "klnrc9"
    - "klnuc1"
    - "lvdec1"
    - "msorc1"
    - "okkdc1"
    - "osbdc1"
    - "osbrc1"
    - "osjnc1"
    - "pokdc1"
    - "prnrc1"
    - "psnrc1"
    - "rdcdc1"
    - "rdkbc1"
    - "rtdec1"
    - "rtnrc1"
    - "spnrc1"
    - "volgc1"
    - "vzvoc1"
    - "START_DATETIME"
    - "END_DATETIME"
src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
