{% set yaml_metadata %}
source_model: "stg_as400__arbvrcpf"
src_pk: "ARTICLE_GOODS_RECEIVED_PALLET_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "ARNRC1"
    - "CYDXC1"
    - "DCKDC1"
    - "EIDEC1"
    - "FANRC1"
    - "FINRC1"
    - "FOEJC1"
    - "FOKDC1"
    - "FONRC1"
    - "GODEC1"
    - "GODFC1"
    - "GOTDC1"
    - "GOUSC1"
    - "IONRC1"
    - "KLNRC1"
    - "LOKNC1"
    - "OPDEC1"
    - "OPTDC1"
    - "PANRC1"
    - "PLAAC3"
    - "PRTYC1"
    - "RTDEC1"
    - "S021C1"
    - "THDEC1"
    - "TIMXC1"
    - "UPDATE_IDENT"
    - "USERC1"
    - "USRXC1"
    - "VEDEC2"
    - "VETDC2"
    - "VEUSC1"
    - "WNNRC1"
    - "WYEJC1"
    - "START_DATETIME"
    - "END_DATETIME"
src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
