{%- set yaml_metadata -%}
source_model: "stg_as400__bestelpf"
src_pk: "GOODS_RECEIVED_LINE_ARTICLE_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "acbdbe"
    - "aiprbe"
    - "akkdbe"
    - "argrbe"
    - "arnrbe"
    - "arombe"
    - "askdbe"
    - "bdbtbe"
    - "bkdtbe"
    - "bkusbe"
    - "bsaabe"
    - "btkdbe"
    - "cnprbe"
    - "dcaabe"
    - "emprbe"
    - "etaabe"
    - "etikbe"
    - "fedtbe"
    - "fekdbe"
    - "feusbe"
    - "gewibe"
    - "godtbe"
    - "gousbe"
    - "inprbe"
    - "ionrbe"
    - "irnrbe"
    - "ivaabe"
    - "jgdtbe"
    - "kobdbe"
    - "kopcbe"
    - "lvnrbe"
    - "odaabe"
    - "oskdbe"
    - "ovaabe"
    - "ovkgbe"
    - "rdkdbe"
    - "stikbe"
    - "tbaabe"
    - "tibdbe"
    - "toaabe"
    - "vpombe"
    - "vrklbe"
    - "zbprbe"
    - "START_DATETIME"
    - "END_DATETIME"
    - "btkdbe_description"
src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
