{%- set yaml_metadata -%}
source_model: "stg_as400__folartpf"
src_pk: "PROMOTION_ARTICLE_HK"
src_hashdiff: "HASHDIFF"
src_payload:
    - "acopgu"
    - "apntgu"
    - "argrgu"
    - "arnrgu"
    - "babdgu"
    - "blkdgu"
    - "bvbdgu"
    - "claagu"
    - "dtdogu"
    - "foejgu"
    - "fokdgu"
    - "fonrgu"
    - "intkgu"
    - "jnkdgu"
    - "kakdgu"
    - "koomgu"
    - "lcnrgu"
    - "lvnrgu"
    - "lykdgu"
    - "oms3gu"
    - "oms4gu"
    - "orbvgu"
    - "pfnrgu"
    - "prblgu"
    - "promgu"
    - "tmdegu"
    - "vndegu"
    - "zgaagu"
src_extra_columns: "END_DATETIME"
src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
