
{%- set yaml_metadata -%}
source_model: "stg_as400__bstalgpf"
src_pk: "PURCHASE_ORDER_HK"
src_hashdiff: "HASHDIFF"
src_payload:
        - "ahalba"
        - "argrba"
        - "bfdtba"
        - "btanba"
        - "cbdtba"
        - "codtba"
        - "dckdba"
        - "dockba"
        - "fedtba"
        - "fekdba"
        - "feusba"
        - "ffdtba"
        - "fgdtba"
        - "fiifba"
        - "finrba"
        - "fkdtba"
        - "fojjba"
        - "fonrba"
        - "gbdtba"
        - "godtba"
        - "gousba"
        - "hkdtba"
        - "hkusba"
        - "i1dtba"
        - "i2dtba"
        - "iodtba"
        - "ionrba"
        - "iosoba"
        - "iousba"
        - "ivdtba"
        - "jfdtba"
        - "jgdtba"
        - "jvdtba"
        - "kkdtba"
        - "lvdtba"
        - "lvnrba"
        - "lvtdba"
        - "ogdtba"
        - "orioba"
        - "podtba"
        - "srdtba"
        - "stkdba"
        - "tacoba"
        - "temoba"
        - "tikoba"
        - "toifba"
        - "toioba"
        - "twioba"
        - "tzboba"
        - "vfdtba"
        - "vvdtba"
        - "vvusba"
        - "zndtba"
        - "znkdba"
        - "look_up_site_code"
        - "START_DATETIME"
        - "END_DATETIME"
        - "stkdba_description"
        - "iosoba_description"
        - "znkdba_description"

src_ldts: "LOAD_DATETIME"
src_source: "RECORD_SOURCE"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(**metadata_dict) }}
