{{ base_data_hub(
    primary_key = [
        'customerid',
        'registrationdate',
        'address.attentionof',
        'address.addressid',
        'address.addresstype',
        'address.addressstatus',
        'address.addressname',
        'address.street',
        'address.housenumber',
        'address.housenumberaddition',
        'address.postalcode',
        'address.city',
        'address.countrycode',
        'address.emailaddress',
        'address.phonenumber',
        'address.phonenumbermobile'
        ],
    payload_columns = [
        'registrationdate',
        'address.attentionof',
        'address.addressid',
        'address.addresstype',
        'address.addressstatus',
        'address.addressname',
        'address.street',
        'address.housenumber',
        'address.housenumberaddition',
        'address.postalcode',
        'address.city',
        'address.countrycode',
        'address.emailaddress',
        'address.phonenumber',
        'address.phonenumbermobile',
    ],
    source_table = 'raw_customer_v1',
    source_extension = ', UNNEST(addresses) AS address'
) }}
