{%- set yaml_metadata -%}
source_model:
    base_stg_slim4__cdc_article_attributes
derived_columns:
    RECORD_SOURCE: "!slim4__cdc_article_attributes"
    LOAD_DATETIME: TIMESTAMP(dt)
    START_DATETIME: TIMESTAMP(dt)
    END_DATETIME: "CAST(NULL AS TIMESTAMP)"
    FORECAST_BK: "artikel_code"
    ARTICLE_BK: "CAST(CAST(code AS INTEGER) AS STRING)"
    SITE_BK: "RTRIM(artikel_code, code)"
    THT_PICK: "SAFE.PARSE_DATE('%d-%m-%Y',tht_pick)"
    VERSTUURDATUM: "SAFE.PARSE_DATE('%Y%m%d',verstuurdatum)"
    VERSTUURDATUM_2: "SAFE.PARSE_DATE('%Y%m%d',verstuurdatum_2)"
    LEVERDATUM: "SAFE.PARSE_DATE('%Y%m%d',leverdatum)"
    LEVERDATUM_2: "SAFE.PARSE_DATE('%Y%m%d',leverdatum_2)"
    IS_STOCK_CONTROLLED: "CAST(CAST(voorraadgestuurd AS INTEGER) AS BOOL)"
hashed_columns:
    ARTICLE_HK: "ARTICLE_BK"
    SITE_HK: "SITE_BK"
    FORECAST_HK : "FORECAST_BK"
    HASHDIFF:
        is_hashdiff: true
        columns:
            - "code"
            - "artikel_code"
            - "abc"
            - "afzet_deze_periode"
            - "aantal_orders"
            - "aantal_maanden_obsolete"
            - "afzet_0"
            - "afzet_1"
            - "afzet_2"
            - "afzet_3"
            - "afzet_4"
            - "afzet_5"
            - "afzet_6"
            - "afzet_7"
            - "afzet_8"
            - "afzet_9"
            - "afzet_10"
            - "afzet_11"
            - "afzet_12"
            - "afzet_13"
            - "afzet_14"
            - "afzet_15"
            - "afzet_16"
            - "afzet_17"
            - "afzet_18"
            - "afzet_19"
            - "afzet_20"
            - "afzet_21"
            - "afzet_22"
            - "afzet_23"
            - "sales_class"
            - "afzet_lopende_week"
            - "afzet_vorige_week"
            - "art_gr"
            - "artikel_omschrijving"
            - "afgerond_besteladvies"
            - "basis_forecast"
            - "bd"
            - "besteladvies"
            - "besteladvies_genereren"
            - "besteld"
            - "bestelfreq"
            - "bestelfreq_bd_levdatum"
            - "bestelniveau"
            - "veiligheidsvoorraad"
            - "buffer_vrd"
            - "cover_tijd_m"
            - "cover_tijd_d"
            - "cover_tijd_w"
            - "dc_locatie"
            - "geimporteerde_eoq"
            - "excess_stock"
            - "f_test_waarde"
            - "forecast_1"
            - "forecast_2"
            - "forecast_3"
            - "forecast_4"
            - "forecast_5"
            - "forecast_6"
            - "forecast_7"
            - "forecast_8"
            - "forecast_9"
            - "forecast_10"
            - "forecast_11"
            - "forecast_12"
            - "folder_info"
            - "forecast_cp"
            - "forecast_cp_vrd"
            - "forecast_exception"
            - "geen_interesse_voorheen_boycot"
            - "gemiddelde_forecast"
            - "ijzeren_voorraad"
            - "ioq"
            - "importartikel"
            - "in_folder"
            - "laatste_afzet"
            - "laatste_maandverkoop"
            - "originele_leverancier"
            - "leveranciersnaam"
            - "levertijd_d"
            - "misorders_manco_lev"
            - "misorders_afgel_wk"
            - "moq"
            - "prijs"
            - "relevante_periode"
            - "bestelinterval_d"
            - "run_code"
            - "scp_naam"
            - "seizoen"
            - "seizoensstatus"
            - "seizoensprofiel"
            - "servicelevel"
            - "setting_ijzeren_vrd"
            - "tht_garantie"
            - "tht_pick"
            - "verkoopprijs"
            - "vest_voorraad_totaal"
            - "voorraadgestuurd"
            - "stock_exception"
            - "voorraadmanager"
            - "fysieke_voorraad"
            - "vrd_min_best_per_max"
            - "werkelijk_te_bestellen"
            - "verstuurdatum"
            - "verstuurdatum_2"
            - "leverdatum"
            - "leverdatum_2"
            - "artikelgroep_omschrijving"
            - "abs_voorspelling"
            - "formule"
            - "st"
            - "totale_veiligheidsvoorraad"
            - "demandplanner_primair"
            - "nullev_leverancier"
            - "gtin"
            - "sales_class_short_description"
            - "sales_class_long_description"
            - "forecast_exception_short_description"
            - "forecast_exception_long_description"
            - "stock_exception_short_description"
            - "stock_exception_long_description"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.stage(**metadata_dict) }}
