{{ base_data_hub(
    primary_key = [
        'customerid',
        'contactperson.contactpersonid',
        'registrationdate',
        'contactperson.countrylanguagecode',
        'contactperson.state',
        'contactperson.contactpersontype',
        'contactperson.initials',
        'contactperson.firstname',
        'contactperson.preposition',
        'contactperson.lastname',
        'contactperson.salutation',
        'contactperson.sex',
        'contactperson.dateofbirth',
        'contactperson.emailaddress',
        'contactperson.phonenumberwork',
        'contactperson.phonenumberhome',
        'contactperson.phonenumbermobile',
        'contactperson.street',
        'contactperson.housenumber',
        'contactperson.housenumberaddition',
        'contactperson.postalcode',
        'contactperson.city',
        'contactperson.countrycode',
        'contactperson.jobposition'
        ],
    payload_columns = [
        'registrationdate',
        'contactperson.countrylanguagecode',
        'contactperson.state',
        'contactperson.contactpersontype',
        'contactperson.initials',
        'contactperson.firstname',
        'contactperson.preposition',
        'contactperson.lastname',
        'contactperson.salutation',
        'contactperson.sex',
        'contactperson.dateofbirth',
        'contactperson.emailaddress',
        'contactperson.phonenumberwork',
        'contactperson.phonenumberhome',
        'contactperson.phonenumbermobile',
        'contactperson.street',
        'contactperson.housenumber',
        'contactperson.housenumberaddition',
        'contactperson.postalcode',
        'contactperson.city',
        'contactperson.countrycode',
        'contactperson.jobposition',
    ],
    source_table = 'raw_customer_v1',
    source_extension = ', UNNEST(contactpersons) AS contactperson'
) }}
