{%- set yaml_metadata -%}
source_model:
    'base_stg_company_info__instellingen'
derived_columns:
    RECORD_SOURCE: "!COMPANY_INFO__Instellingen"
    LOAD_DATETIME: "TIMESTAMP(dt)"
    END_DATETIME: "CAST(NULL AS TIMESTAMP)"
    COMPANY_REFERENCE_BK: "sizokey"
    PARENT_COMPANY_BK: "sizokey_md"
    ULTIMATE_PARENT_COMPANY_BK: "sizokey_up"
    COMPANY_ADDRESS_BK: "sizolocidm"
    COMPANY_BUILDING_BK: "bagopndid"
    POSTCODE_BK: "CAST(SIZOPCD4 AS INT64)"
    SIZDVRH: "DATE(SIZDVRH)"
    SIZDNMW: "DATE(SIZDNMW)"
    SIZDOPR: "DATE(SIZDOPR)"
    SIZTVRHDAT: "PARSE_DATE('%Y%m%d', SIZTVRHDAT)"
    SIZTNMWDAT: "PARSE_DATE('%Y%m%d', SIZTNMWDAT)"
    SIZOPCD: "REPLACE(SIZOPCD, ' ', '')"
    SIZOCPCD: "REPLACE(SIZOCPCD, ' ', '')"
    SIZOPBPCD: "REPLACE(SIZOPBPCD, ' ', '')"
    SAT_DETAILS: "!rv_sat__company_reference_details"
hashed_columns:
    COMPANY_REFERENCE_HK:
        - "COMPANY_REFERENCE_BK"
    PARENT_COMPANY_HK:
        - "PARENT_COMPANY_BK"
    ULTIMATE_PARENT_COMPANY_HK:
        - "ULTIMATE_PARENT_COMPANY_BK"
    COMPANY_ADDRESS_HK:
        - "COMPANY_ADDRESS_BK"
    COMPANY_BUILDING_HK:
        - "COMPANY_BUILDING_BK"
    POSTCODE_HK:
        - "POSTCODE_BK"
    COMPANY_REFERENCE_HIERARCHY_HK:
        - "COMPANY_REFERENCE_BK"
        - "PARENT_COMPANY_BK"
        - "ULTIMATE_PARENT_COMPANY_BK"
    COMPANY_REFERENCE_ADDRESS_POSTCODE_HK:
        - "COMPANY_REFERENCE_BK"
        - "COMPANY_ADDRESS_BK"
        - "POSTCODE_BK"
    COMPANY_REFERENCE_BUILDING_HK:
        - "COMPANY_REFERENCE_BK"
        - "COMPANY_BUILDING_BK"
    COMPANY_REFERENCE_LOCATION_HK:
        - "COMPANY_REFERENCE_BK"
        - "POSTCODE_BK"
    HASHDIFF:
        is_hashdiff: true
        columns:
            - "sizokey"
            - "sizokey_md"
            - "sizokey_up"
            - "sizolockey"
            - "sizolocidm"
            - "sizokix"
            - "sizopcd4"
            - "bagopndid"
            - "sizokvk"
            - "sizorsin"
            - "sizoves"
            - "sizonm"
            - "sizostn"
            - "sizohn1"
            - "sizohn2"
            - "sizohn3"
            - "sizonm_up"
            - "sizoadr"
            - "sizostr"
            - "sizohnr"
            - "sizothn"
            - "sizopcd"
            - "sizoplt"
            - "sizocadr"
            - "sizocstr"
            - "sizochnr"
            - "sizocthn"
            - "sizocpcd"
            - "sizocplt"
            - "sizopbadr"
            - "sizopbpb"
            - "sizopbnr"
            - "sizopbpcd"
            - "sizopbplt"
            - "sizotel"
            - "sizttel"
            - "sizotelv"
            - "sizttelv"
            - "sizotelm"
            - "sizttelm"
            - "selloph"
            - "selladrft"
            - "sellmlst"
            - "selkjurent"
            - "sellbdm"
            - "sellbtm"
            - "sellimp"
            - "sellexp"
            - "sizlbmn"
            - "sizlio"
            - "sizcbyztyp"
            - "sizlhfdgbr"
            - "sizocilink"
            - "sizwam"
            - "sizkam"
            - "sizosbi"
            - "sizosbi2"
            - "sizosbiseg"
            - "sizonace"
            - "sizchnv"
            - "sizcrv"
            - "sizkrv"
            - "sizdopr"
            - "sizwoprjr"
            - "siztoprdat"
            - "sizwlft"
            - "sizklft"
            - "sizwfil"
            - "sizcbnc1"
            - "sizkbnc1"
            - "sizobtw"
            - "sizpmarbr"
            - "sizkmarbr"
            - "sizpcloba"
            - "sizkcloba"
            - "sizlint"
            - "sellbrv"
            - "sizourl"
            - "sizckvkdis"
            - "sizctypove"
            - "sizctypond"
            - "sizofr_frm"
            - "sizcfr_srt"
            - "sizcfr_gev"
            - "sizcfr_nem"
            - "sizcfr_rel"
            - "sizlmdmu_l"
            - "sizlmdmu_c"
            - "sizoskdmul"
            - "sizoskdmuc"
            - "sizcbeslv"
            - "sizlbdmu_l"
            - "sizocontlr"
            - "sizoloctlr"
            - "sizwhinivo"
            - "sizccorel"
            - "sizostart"
            - "sizcstart"
            - "sizczzp"
            - "sizczzptyp"
            - "sizdvrh"
            - "siztvrhdat"
            - "sizdnmw"
            - "siztnmwdat"
            - "sizobmkey"
            - "sizrsortc"
            - "sizwboom"
            - "creckredwa"
            - "sizlverrv"
            - "sizcveradr"
            - "sellip"
            - "sellsubsde"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.stage(**metadata_dict) }}
