-- This staging is created by sql script instead of automateDV template
-- This is because the data is generated by using a dbt package instead of from a source system.

WITH
date_dimension AS (
    {{ dbt_date.get_date_dimension(var('ref_calendar_start_date'), var('ref_calendar_end_date')) }}
),

staging AS (
    SELECT
        date_day AS calendar_date_nk,
        'GENERATED__dbt-date' AS record_source,
        prior_date_day,
        next_date_day,
        prior_year_date_day,
        prior_year_over_year_date_day,
        day_of_week,
        day_of_week_iso,
        day_of_week_name,
        day_of_week_name_short,
        day_of_month,
        day_of_year,
        week_start_date,
        week_end_date,
        prior_year_week_start_date,
        prior_year_week_end_date,
        week_of_year,
        iso_week_start_date,
        iso_week_end_date,
        prior_year_iso_week_start_date,
        prior_year_iso_week_end_date,
        iso_week_of_year,
        prior_year_week_of_year,
        prior_year_iso_week_of_year,
        month_of_year,
        month_name,
        month_name_short,
        month_start_date,
        month_end_date,
        prior_year_month_start_date,
        prior_year_month_end_date,
        quarter_of_year,
        quarter_start_date,
        quarter_end_date,
        year_number,
        year_start_date,
        year_end_date,
        CURRENT_TIMESTAMP() AS load_datetime,
        FORMAT_DATE('%A', CAST(week_start_date AS date)) AS first_day_of_week_name,
        FORMAT_DATE('%A', CAST(iso_week_start_date AS date)) AS iso_first_day_of_week_name,

        -- The week_of_year (non-ISO based) starts from 0 if the 1st of january falls in the middle of a week
        -- The year of_week calculates on which year does the week belongs to.
        -- The logic below is to handle a cross-year week
        IF(week_of_year <= 1, EXTRACT(YEAR FROM week_end_date), EXTRACT(YEAR FROM week_start_date)) AS year_of_week,
        IF(iso_week_of_year = 1, EXTRACT(YEAR FROM iso_week_end_date), EXTRACT(YEAR FROM iso_week_start_date))
            AS iso_year_of_week,

        -- Four week period calculation : week number / 4. Round the period to 13 if a year has 53 weeks
        CAST(IF(iso_week_of_year > 52, 13, CEIL(iso_week_of_year / 4)) AS integer) AS iso_four_week_period,

        (date_day = month_end_date) AS last_day_of_month_indicator,
        IF(day_of_week_iso >= 6, 'Weekend', 'Weekday') AS iso_weekday_weekend_indicator
    FROM date_dimension
)

SELECT * FROM staging
