{%- set yaml_metadata -%}
source_model:
    'base_as400__bstalgpf'
derived_columns:
    RECORD_SOURCE: "!AS400__bstalgpf"
    LOAD_DATETIME: "{{ fivetran_last_touched() }}"
    EFFECTIVE_FROM: "_fivetran_start"
    START_DATETIME: "_fivetran_start"
    END_DATETIME: "{{ fivetran_end() }}"
    PURCHASE_ORDER_BK: "TRIM(CAST(ionrba AS STRING))"
    GOODS_RECEIVED_BK: "TRIM(CAST(ionrba AS STRING))"
    SUPPLIER_BK: "NULLIF(TRIM(CAST(lvnrba AS STRING)),'0')"
    SITE_BK: "NULLIF(TRIM(CAST(look_up_site_code AS STRING)),'0')"
    cbdtba: "{{ cast_to_date('cbdtba') }}"
    codtba: "{{ cast_to_date('codtba') }}"
    dckdba: "NULLIF(TRIM(dckdba), '')"
    finrba: "UPPER(NULLIF(TRIM(CAST(finrba AS STRING)),'0'))"
    fojjba: "{{ sfg_cast_to_year('fojjba') }}"
    gbdtba: "{{ cast_to_date('gbdtba') }}"
    godtba: "{{ cast_to_date('godtba') }}"
    gousba: "NULLIF(TRIM(gousba), '')"
    iodtba: "{{ cast_to_date('iodtba') }}"
    iosoba: "NULLIF(TRIM(iosoba), '')"
    znkdba: "NULLIF(TRIM(znkdba), '')"
    iousba: "NULLIF(TRIM(iousba), '')"
    i1dtba: "{{ cast_to_date('i1dtba') }}"
    i2dtba: "{{ cast_to_date('i2dtba') }}"
    ionrba: "UPPER(NULLIF(TRIM(CAST(ionrba AS STRING)), ''))"
    ivdtba: "{{ cast_to_date('ivdtba') }}"
    jfdtba: "{{ cast_to_date('jfdtba') }}"
    jgdtba: "{{ cast_to_date('jgdtba') }}"
    kkdtba: "{{ cast_to_date('kkdtba') }}"
    lvnrba: "UPPER(NULLIF(TRIM(CAST(lvnrba AS STRING)), ''))"
    lvdtba: "{{ cast_to_date('lvdtba') }}"
    zndtba: "{{ cast_to_date('zndtba') }}"
    feusba: "NULLIF(TRIM(feusba), '')"
    look_up_site_code: "UPPER(NULLIF(TRIM(CAST(look_up_site_code AS STRING)), ''))"

hashed_columns:
    PURCHASE_ORDER_HK:
        - "PURCHASE_ORDER_BK"
    SUPPLIER_HK:
        - "SUPPLIER_BK"
    GOODS_RECEIVED_HK:
        - "GOODS_RECEIVED_BK"
    SUPPLIER_HK:
        - "SUPPLIER_BK"
    SITE_HK:
        - "SITE_BK"
    PURCHASE_ORDER_SITE_SUPPLIER_HK:
        - "PURCHASE_ORDER_BK"
        - "SITE_BK"
        - "SUPPLIER_BK"
    GOODS_RECEIVED_PURCHASE_ORDER_SITE_SUPPLIER_HK:
        - "GOODS_RECEIVED_BK"
        - "PURCHASE_ORDER_BK"
        - "SITE_BK"
        - "SUPPLIER_BK"

    HASHDIFF:
        is_hashdiff: true
        columns:
            - "ahalba"
            - "argrba"
            - "bfdtba"
            - "btanba"
            - "cbdtba"
            - "codtba"
            - "dckdba"
            - "dockba"
            - "fedtba"
            - "fekdba"
            - "feusba"
            - "ffdtba"
            - "fgdtba"
            - "fiifba"
            - "finrba"
            - "fkdtba"
            - "fojjba"
            - "fonrba"
            - "gbdtba"
            - "godtba"
            - "gousba"
            - "hkdtba"
            - "hkusba"
            - "i1dtba"
            - "i2dtba"
            - "iodtba"
            - "ionrba"
            - "iosoba"
            - "iousba"
            - "ivdtba"
            - "jfdtba"
            - "jgdtba"
            - "jvdtba"
            - "kkdtba"
            - "lvdtba"
            - "lvnrba"
            - "lvtdba"
            - "ogdtba"
            - "orioba"
            - "podtba"
            - "srdtba"
            - "stkdba"
            - "tacoba"
            - "temoba"
            - "tikoba"
            - "toifba"
            - "toioba"
            - "twioba"
            - "tzboba"
            - "vfdtba"
            - "vvdtba"
            - "vvusba"
            - "zndtba"
            - "znkdba"
            - "look_up_site_code"
            - "_fivetran_start"
            - "_fivetran_end"
            - "stkdba_description"
            - "iosoba_description"
            - "znkdba_description"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.stage(**metadata_dict) }}
